import { createRoot, type Root } from 'react-dom/client';
import { createElement, isValidElement, type ComponentType, type ReactNode } from 'react';

const roots = new WeakMap<Element, Root>();

export interface StoryParameters {
  /** Container layout preset. */
  layout?: 'centered' | 'fullscreen' | 'padded';
  /** Background colour for the story preview. */
  background?: string;
}

interface MountOptions {
  /**
   * Decorators applied outer-to-inner: `[A, B]` produces
   * `<A><B><Story /></B></A>`. Each must be a component that receives
   * `{ children }`.
   */
  decorators?: ComponentType<{ children: ReactNode }>[];
  isolation?: 'shadow';
  /** Initial / current props passed to the story render function. */
  args?: Record<string, unknown>;
  /** Per-story display parameters applied to the placeholder element. */
  parameters?: StoryParameters;
  /**
   * CSS string to inject before mounting, generated by Markbook's embed
   * bundler. Injected into the shadow root when `isolation: 'shadow'`,
   * otherwise into `document.head` (dedup-keyed on `cssId`).
   */
  css?: string;
  /** Stable id used to dedup the light-DOM `<style>` tag. */
  cssId?: string;
}

const LAYOUT_CLASSES = [
  'markbook-story--centered',
  'markbook-story--fullscreen',
  'markbook-story--padded',
];

export function mount(el: Element | null, story: unknown, opts?: MountOptions): void {
  if (!el) return;

  applyParameters(el, opts?.parameters);
  const target = resolveMountTarget(el, opts);
  injectCss(target, opts);

  let root = roots.get(target);
  if (!root) {
    root = createRoot(target);
    roots.set(target, root);
  }

  let element: ReactNode;
  if (typeof story === 'function') {
    element = createElement(story as ComponentType, opts?.args ?? null);
  } else if (isValidElement(story)) {
    element = story;
  } else {
    throw new Error('Markbook: story export must be a function component or a React element');
  }

  if (opts?.decorators && opts.decorators.length > 0) {
    for (let i = opts.decorators.length - 1; i >= 0; i--) {
      element = createElement(opts.decorators[i]!, null, element);
    }
  }

  root.render(element);
}

function applyParameters(el: Element, params: StoryParameters | undefined): void {
  if (!params) return;
  const host = el as HTMLElement;
  for (const cls of LAYOUT_CLASSES) host.classList.remove(cls);
  if (params.layout) host.classList.add(`markbook-story--${params.layout}`);
  if (params.background !== undefined) host.style.background = params.background;
}

function resolveMountTarget(el: Element, opts?: MountOptions): Element {
  if (opts?.isolation !== 'shadow') return el;
  const host = el as HTMLElement;
  let shadow = host.shadowRoot;
  if (!shadow) shadow = host.attachShadow({ mode: 'open' });
  let container = shadow.querySelector('.markbook-shadow-host') as HTMLElement | null;
  if (!container) {
    container = document.createElement('div');
    container.className = 'markbook-shadow-host';
    shadow.appendChild(container);
  }
  return container;
}

/**
 * Inject the bundle's CSS into the appropriate scope.
 *
 * - When `target` is inside a shadow root, append a `<style>` to the shadow
 *   root (one per cssId — re-mounts of the same bundle into the same shadow
 *   don't duplicate).
 * - Otherwise, append to `document.head`, deduplicating across the whole page
 *   via `data-markbook-css="<cssId>"`.
 */
function injectCss(target: Element, opts?: MountOptions): void {
  const css = opts?.css;
  if (!css) return;
  const cssId = opts?.cssId ?? '';

  const root = target.getRootNode();
  if (root instanceof ShadowRoot) {
    if (cssId && root.querySelector(`style[data-markbook-css="${cssId}"]`)) return;
    const style = document.createElement('style');
    if (cssId) style.setAttribute('data-markbook-css', cssId);
    style.textContent = css;
    root.appendChild(style);
    return;
  }

  if (cssId && document.head.querySelector(`style[data-markbook-css="${cssId}"]`)) return;
  const style = document.createElement('style');
  if (cssId) style.setAttribute('data-markbook-css', cssId);
  style.textContent = css;
  document.head.appendChild(style);
}

export type { MountOptions };
export { setupControls } from './controls.js';
export type { ArgType } from './controls.js';
