/**
 * Browser-side runtime helpers shared by every Markbook framework adapter
 * (`@markbook/adapter-react`, `-vue`, `-wc`). Pure DOM — NO Node and NO
 * framework imports — so it bundles cleanly into the adapters' default
 * browser entry without violating the two-entry split (ADR-0005).
 *
 * Each adapter wires its own `mount()` (and React additionally `setupControls`)
 * but the placeholder/shadow/CSS plumbing is identical, so it lives here.
 */

export interface StoryParameters {
  /** Container layout preset. */
  layout?: 'centered' | 'fullscreen' | 'padded';
  /** Background colour for the story preview. */
  background?: string;
}

/**
 * The framework-agnostic subset of every adapter's `MountOptions`. React and
 * Vue extend this with `args` plus their own decorator type; web components
 * use it as-is. Deliberately does NOT include `args`/`decorators` so an
 * adapter can't accidentally advertise support it doesn't implement.
 */
export interface BaseMountOptions {
  /** Wrap the mount in an open shadow root so host-page CSS can't leak in. */
  isolation?: 'shadow';
  /** Per-story display parameters applied to the placeholder element. */
  parameters?: StoryParameters;
  /**
   * CSS string to inject before mounting, generated by Markbook's embed
   * bundler. Injected into the shadow root when `isolation: 'shadow'`,
   * otherwise into `document.head` (dedup-keyed on `cssId`).
   */
  css?: string;
  /** Stable id used to dedup the light-DOM `<style>` tag. */
  cssId?: string;
}

const LAYOUT_CLASSES = [
  'markbook-story--centered',
  'markbook-story--fullscreen',
  'markbook-story--padded',
];

/**
 * Apply per-story display parameters to the placeholder element: swap the
 * `markbook-story--<layout>` class and set an optional background.
 */
export function applyParameters(el: Element, params: StoryParameters | undefined): void {
  if (!params) return;
  const host = el as HTMLElement;
  for (const cls of LAYOUT_CLASSES) host.classList.remove(cls);
  if (params.layout) host.classList.add(`markbook-story--${params.layout}`);
  if (params.background !== undefined) host.style.background = params.background;
}

/**
 * Resolve where a story should mount.
 *
 * - Without isolation: the placeholder element itself.
 * - With `isolation: 'shadow'`: a `.markbook-shadow-host` div inside an open
 *   shadow root (created on first use). Mounting into the inner div — rather
 *   than the shadow root directly — keeps any injected `<style>` as a
 *   sibling, so an adapter's "clear previous render" pass only touches the
 *   story, not the stylesheet.
 */
export function resolveMountTarget(el: Element, isolation: 'shadow' | undefined): HTMLElement {
  if (isolation !== 'shadow') return el as HTMLElement;
  const host = el as HTMLElement;
  let shadow = host.shadowRoot;
  if (!shadow) shadow = host.attachShadow({ mode: 'open' });
  let container = shadow.querySelector('.markbook-shadow-host') as HTMLElement | null;
  if (!container) {
    container = document.createElement('div');
    container.className = 'markbook-shadow-host';
    shadow.appendChild(container);
  }
  return container;
}

/**
 * Inject the bundle's CSS into the appropriate scope.
 *
 * - When `target` is inside a shadow root, append a `<style>` to the shadow
 *   root (one per `cssId` — re-mounts of the same bundle into the same shadow
 *   don't duplicate).
 * - Otherwise, append to `document.head`, deduplicating across the whole page
 *   via `data-markbook-css="<cssId>"`.
 */
export function injectCss(
  target: Element,
  css: string | undefined,
  cssId: string | undefined,
): void {
  if (!css) return;
  const id = cssId ?? '';

  const root = target.getRootNode();
  if (root instanceof ShadowRoot) {
    if (id && root.querySelector(`style[data-markbook-css="${id}"]`)) return;
    const style = document.createElement('style');
    if (id) style.setAttribute('data-markbook-css', id);
    style.textContent = css;
    root.appendChild(style);
    return;
  }

  if (id && document.head.querySelector(`style[data-markbook-css="${id}"]`)) return;
  const style = document.createElement('style');
  if (id) style.setAttribute('data-markbook-css', id);
  style.textContent = css;
  document.head.appendChild(style);
}
